### PR TITLE
Add a verified HashSet implementation + refactor package name of map + add script

### PR DESCRIPTION
**Pull request by samuelchassot**
Includes a renaming of the packages in the mutableMaps project.

### CODE REVIEW

**Comment by samuelchassot** [comment]
Also preparing the verify.sh scripts to run the Stainless CI

**Comment by vkuncak** [comment]
I merged epfl-lara/stainless#1574 . This one has some conflicts?

**Comment by samuelchassot** [comment]
I don't know why, git merged it automatically. Anyway, now we're good :)

**Comment by vkuncak** [comment]
@samuelchassot  As far as I can tell, it looks good to me. I hope you ran it on a laraquad to check it should work with nightly script.

Note that I still do see "This branch cannot be rebased due to conflicts"

**Comment by samuelchassot** [comment]
@vkuncak I'll set up a CI for bolts tomorrow, so we can wait to make sure 👍 
Weird, I'll check tomorrow the merge thing.

**Pull request merged**
