### PR TITLE
Add 2 versions of a lexing framework, with DFA and Regex, which are also verified

### PR DESCRIPTION
**Pull request by samuelchassot**

### CODE REVIEW

**Comment by samuelchassot** [comment]
I ran `stainless` with the `stainless.conf.nightly` and it passes on my machine, in around 13min total (for both regex and dfa).

**Review by mario-bucev — APPROVED** [review]
Ran it as well on my machine, and everything verifies, excellent job :+1:!

**Comment by samuelchassot** [comment]
Thanks :) 
Should we move it outside WIP or we keep it there?

**Comment by samuelchassot** [comment]
Done!

**Comment by mario-bucev** [comment]
@vkuncak This can be merged

**Pull request merged**
